// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olnymfbyoaqintzlfrdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sbnltZmJ5b2FxaW50emxmcmRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3NDAyMjcsImV4cCI6MjA1MzMxNjIyN30.ThI1olvv_fcQV_y8zFXx73gGoUymlOifcrbu8BGALZ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);